### ISSUE TITLE
 [GigEV][PhoXiAPI] MotionCam FPS with color

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#2]
I am trying to get high fps with color both over GigEV and API (just experimenting in PhoXi control)

---------------------------------------------------

With:
- `OutputToplogy = RegularGrid`
- `TextureSource = Color`
- only enabled output for depth and texture
- both 1288x730 and 1932x1096 color resolution

I can get around 10 fps

-----------------------------

The only way I can get near 20 fps is:
- `OutputToplogy = Raw`
- `TextureSource = Laser`

But this means:
- no possibility to model optics with camera matrix/distortion
  - in general incompatibility with other tools I need
- no color information

-------------------------------------------

Is this expected when working with color/regular grid?

Are there some settings that I could set to get more fps with color?
- tried a few
  - `Exposure` is already at lowest 10 ms

**Comment by bmegli** [comment]
For GigEV I tried also:
- larger MTU on transport layer (9000)
- restarting the camera (power cycle)
- setting MotionCam `GevSCPSPacketSize` to match MTU size


```bash
# setting MTU
sudo ifconfig enp60s0 mtu 9000
```


But that had no measurable difference on FPS

**Comment by patrikdaniel** [comment]
Dear Bartosz, 

> With:
OutputToplogy = RegularGrid
TextureSource = Color
only enabled output for depth and texture
both 1288x730 and 1932x1096 color resolution
I can get around 10 fps

Indeed, this is the highest FPS you can reach in this setup.  In order to reach an average of 12 FPS with the Color information, you could switch to the OutputToplogy = `Irregular grid`

![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/16776605/a2b189ee-3a10-4dec-b2e6-d1305fbfe13f)

In this setup, the following table demonstrates the average FPS values one can obtain:
![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/16776605/d04d23ab-eac2-4016-aaa5-37a6191c4e6a)

Of course, we are working hard to improve our current results and increasing FPS is on the roadmap but the exact dates are not set yet. As for now, the resolution, accuracy, and output FPS of the MotionCam-3D Color still represent rather difficult targets to achieve by any other 3D sensor on the market.

**Comment by bmegli** [comment]
Thank you @patrikdaniel,

For the `IrregularGrid` over GigE-Vision I can only get 560x800 data (see #3)

But our main concern with `IrregularGrid` is no possibility to model optics with camera matrix/distortion.

In our case reprojection map is not a great solution:
- we are streaming compressed depth/rgb data with optical model
- and rebuilding 3D in remote location
- we don't want to stream also reprojection map which would require extra lossless compression

Is there any analytical process available to rebuild reprojection map from parametric model on remote side (like quirky optical model)?

**Comment by patrikdaniel** [comment]
Hi @bmegli, 

I'll respond to #3 in the respective thread.

I just wanted to let you know that there is no need to _stream_ also the reprojection map. You can retrieve it only once and then multiply the depth map information always by the same reprojection map. You need to retrieve a new reprojection map only in case of changing the Output Topology/Operation Mode, in all other cases the reprojection map remains constant.

Concerning the analytical process, all Photoneo 3D sensors use a pin-hole camera model extended by radial and tangential distortion (same as used by OpenCV). Please note, that the standard pin-hole camera model with distortion works to project points from the world coordinate system to the image pixels space. Hence, if one wants to reproject the depth map to a point cloud, it is necessary to turn the projection backwards from the image pixels space to the world coordinate system (camera space). In our case, it is done by computation of the inverse of distortion functions (numerically). The whole situation is further complicated by the proprietary design of the image sensor used in all products from the MotionCam-3D product family. We do not share the underlying algorithm with customers and only provide the pre-computed reprojection map.

**Comment by bmegli** [comment]
Thanks,

> I just wanted to let you know that there is no need to stream also the reprojection map. You can retrieve it only once and then multiply the depth map information always by the same reprojection map. You need to retrieve a new reprojection map only in case of changing the Output Topology/Operation Mode, in all other cases the reprojection map remains constant.

Sure, I am aware of that.

In our use cases where we get the data from the camera may be different geographical location from where we reconstruct 3D. So reprojection map would need to be sent at least once as metadata or stored as "calibration".

> Concerning the analytical process, all Photoneo 3D sensors use a pin-hole camera model extended by radial and tangential distortion [...] We do not share the underlying algorithm with customers and only provide the pre-computed reprojection map.

No worries, we are happy with `RegularGrid` topology and Brown-Conrady distortion model variants which are directly compatible with our pipelines. 

-------------------------------------------------

The technical details of framerates achievable with various settings and current firmware/software combination answers the original question.
