### ISSUE TITLE
 [GigEV] MotionCam `OutputTopology==IrregularGrid` results in 560x800 resolution

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#3]
Related to #1 

This is different behavior compared to PhoXi Control which gets 1120x800 with `Irregular grid`

Also, according to documentation "Grids" topology should result in 1120x800

> Scanning Guide/Scanning Parameters/Capturing parameters (MotionCam-3D)/Camera Mode (MotionCam-3D)

![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/7d86bcc3-2029-4e92-9f08-ca7f6fbd8d3f)

## PhoXi Control

Workflow: Change topology -> Set -> Free run -> Readout reported resolution/look and output data resolution

| `OutputTopology` | Reported resolution | Screenshot |
|------------------------|-----------------------------|-----------------| 
|     `Raw`              |  560x800   | ![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/372fdd34-38c8-4abd-8e96-b4e7685b63ea) |
| `Regular grid`           | 1120x800 |  ![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/2b1337d9-b928-46bf-ad9f-6b5e688b2acc) |
| `Irregular grid` | 1120x800  | ![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/3d21d91c-137d-4bce-8114-f39783ca613c) |

## GigEV

| `OutputTopology` | Reported resolution |
|------------------------|-----------------------------|
|     `Raw`              |  560x800   | 
| `RegularGrid`           | 1120x800 |
| `IrregularGrid` | 560x800  |

`arv-tool` here illustrates the problem. The data I get over GigE-Vision is also 560x800 with `IrregularGrid`

```bash
arv-tool-0.8 control OutputTopology=Raw Width Height
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
OutputTopology = Raw
Width = 560 min:0 max:4294967295
Height = 800 min:0 max:4294967295
```

```bash
arv-tool-0.8 control OutputTopology=RegularGrid Width Height
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
OutputTopology = RegularGrid
Width = 1120 min:0 max:4294967295
Height = 800 min:0 max:4294967295
```

```bash
arv-tool-0.8 control OutputTopology=IrregularGrid Width Height
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
OutputTopology = IrregularGrid
Width = 560 min:0 max:4294967295
Height = 800 min:0 max:4294967295
```

## Question

Is this expected? Is there anything else I should do to get 1120x800 resolution with `IrregularGrid`?

**Comment by bmegli** [comment]
Also this output may be handy

```bash
arv-tool-0.8 control OutputTopology=IrregularGrid CameraResolution Width Height
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
OutputTopology = IrregularGrid
CameraResolution = Resolution_1120x800
Width = 560 min:0 max:4294967295
Height = 800 min:0 max:4294967295
```

```bash
arv-tool-0.8 control OutputTopology=RegularGrid CameraResolution Width Height
Photoneo-MotionCam-3D Color-TRD-058 (192.168.0.194)
OutputTopology = RegularGrid
CameraResolution = Resolution_1120x800
Width = 1120 min:0 max:4294967295
Height = 800 min:0 max:4294967295
```

**Comment by patrikdaniel** [comment]
@bmegli, unfortunately, you ran into an inconsistency between PhoXi API and our GigEV interface (in FW 1.10.1).  

For `IrregularGrid` there is an additional data processing performed on the PhoXi Control side after retrieving the data from the device. This has been implemented in the GigEV firmware version to be done already on the device side, but only for `RegularGrid`.

Thanks for pointing out the bug when `CameraResolution = Resolution_1120x800` is reported for `OutputTopology = IrregularGrid`.  I suggest that you use the `RegularGrid`  which is a more natural choice. 

For the upcoming FW releases, we are also working on new Output Topologies which should lead to an even better user experience.

**Comment by bmegli** [comment]
Thank you for clarifying that.

Yes, we are working with `RegularGrid` anyway as it is directly compatible with our pipelines.

`IrregularGrid` was just mentioned in the context of #1 and #2 discussions.

Kind regards.
