### ISSUE TITLE
[GigEV] Is color texture pixel format reversible YCoCg-R? (not custom YCoCg)

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#4]
# Overview

- the documentation states that color pixel format is custom `YCoCg`

https://github.com/photoneo-3d/photoneo-cpp-examples/blob/057428aa15b54234c385712e88e92ddaae90246c/GigEV/README.md?plain=1#L120-L123

- what I see after inspecting code is reversible `YCoCg-R`

# YCoCg(-R) -> RGB

In provided [sample implementation](https://github.com/photoneo-3d/photoneo-cpp-examples/blob/057428aa15b54234c385712e88e92ddaae90246c/GigEV/aravis/common/YCoCg.h#L50)
- omitting the 4:2:0 chroma subsampling part
- and focusing on conversion to RGB

![ycocg_r](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/a0676028-5e65-4bfa-b75e-91ec743754e7)

Apart from:
- trying hard to avoid signed integers
- extra check for `y == 0`
- this implements reversible `YCoCg-R` as defined in many standards

Annotated excerpt from [VESA DSC](https://glenwing.github.io/docs/VESA-DSC-1.2.pdf) 7.7 Color Space Conversions

![VESA_YCoCg-R](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/0b61928e-dcdd-4ce3-ba41-af0bca022353)

# Deviation from standard

The only deviation from standard revesible `YCoCg-R` is:
- extra check for `y == 0`

# Question

1. Could you confirm/deny that pixel format you are using is `YCoCg-R`, not custom `YCoCg`?
2. Is the extra check for `y == 0` necessary for some reason? Are you for example marking invalid data with it on sender side?
2.1. Specifically I am interested if you follow the standard formulation of `YCoCg-R` on the sender side (attached in next post)

**Comment by bmegli** [comment]
# RGB -> YCoCg-R

For reference to question 2.1, this is device side (sender)
- `convert_rgb` would be 1
- `bits_per_component` would be 10

[VESA DSC](https://glenwing.github.io/docs/VESA-DSC-1.2.pdf) 6.1 Color Space Conversions

![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/eb9fbeca-ab49-4632-b3c2-510601954fe5)

**Comment by JakubImriskaPhotoneo** [comment]
Dear @bmegli,
indeed, the extra check of `y == 0` is used to protect black pixels, which is needed to be addressed explicitly in the case with _chroma subsampling_.
Apart from the _chroma subsampling_ (with the _black pixel protection_) there are few subtle differences with respect to the standard `YCoCg-R`:
 * rounding differences, as `1024 - (co + cg) / 2` might differ from `-(co - 1024) / 2 - (cg - 1024)/2` in an integer arithmetic,
 * in the encoding, our `Co`, `Cg` differ by 1: `Co = cscCo + maxVal`, `Cg = cscCg + maxVal` (which might be suboptimal in terms of information loss).

Note: The formulas for 16bpc in the last paragraph of the referenced section 6.1 contain the bit shift operator `>>` which is apparently an error.

**Comment by bmegli** [comment]
Thank you @JakubImriskaPhotoneo,

I will relate fragment by fragment

## y==0 check

> indeed, the extra check of `y == 0` is used to protect black pixels, which is needed to be addressed explicitly in the case with _chroma subsampling_.

Right! I forgot about chroma subsampling and the fact there is only one chroma sample in 2x2 group.

And mapping `y==0` doesn't loose other color information that could potentially clash, because there are no other RGB colors that map to `y==0` apart from black. In other words `y==0` check will not destroy other color information. I understand this now.

Looking at color cuboids vertices there are more such "special channels" that could convey extra information.

| Below for YCoCg, but yours/YCoCg-R differs only in scaled Co/Cg axes ([source](https://spec.oneapi.io/oneipl/0.6/concepts/color-models.html))   |
|----|
| ![image](https://github.com/photoneo-3d/photoneo-cpp-examples/assets/9095769/434633b0-0f0c-4b49-846f-2e08f728ccec) |

**Comment by bmegli** [comment]
> Note: The formulas for 16bpc in the last paragraph of the referenced section 6.1 contain the bit shift operator >> which is apparently an error.

Good funny catch.
It is fixed in any subsequent revision of VESA DSC but 16 bits per component is not our case.

---------------------------------------------

10^82 - atoms in universe
2^32768 - this would zero out the ... multiverse?

I always wanted to put my hands on 32768 bit processor... 
32768/8=4096 bytes?

They make them this way so that standard 4KB memory page fits in a single integer.

**Comment by bmegli** [comment]
> rounding differences, as 1024 - (co + cg) / 2 might differ from -(co - 1024) / 2 - (cg - 1024)/2 in an integer arithmetic,

Truncation differences. As a digression, YCoCg-R is designed in such way that even if truncation happens it reverses back to original values.

This should not differ by more than 1 bit in result.

>  in the encoding, our Co, Cg differ by 1: Co = cscCo + maxVal, Cg = cscCg + maxVal (which might be suboptimal in terms of information loss).

Interesting. But in sample decoding you are working with delta = 512 = 1024/2 and 2*delta = 1024
Is this intended?

In any case, without putting any more thought in it, this should not differ by more than 1 bit in result.

**Comment by bmegli** [comment]
And we arrive at conclusion.

As I am scaling the final 10 bit RGB values to 8 bit RGB values effectively loosing 2 LSB bits
in my special word your pixel format is equivalent to YCoCg-R aside from `y==0` checks.

---------------------------------------------------------

So the answer is probably nuanced
- it is almost VESA `YCoCg-R`
  - much closer to it than to `YCoCg` as you are using same `Co` ,`Cg` scaling
  - has extra protection of black pixels in chroma subsampling
- when converting to 8 bit-per-pixel RGB it behaves as `YCoCg-R` (+ `y==0` check)

**Comment by JakubImriskaPhotoneo** [comment]
@bmegli Thanks for summarization. I'll update the related documentation and fix the suboptimality (`maxVal` -> `1 << bits_per_component`) in the encoding.

**Comment by bmegli** [comment]
Thanks!

All my questions were answered and changes on LSbs will not affect my 8 bit-per-channel RGB world anyway.

I admit I have some trouble discerning subtle shades of 2^30 ~= 1000,000,000 colors
