### ISSUE TITLE
[GigEV] `Laser`/`LED` texture source bit depth

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#5]
As documented, `Intensity` is always delivered as GigEV/GenICam `Mono16`but real data inside varies. 

https://github.com/photoneo-3d/photoneo-cpp-examples/blob/ffd76804b863c10b9dd1164525740e29c4320192/GigEV/README.md?plain=1#L114-L116

Can any assumption be made for `Laser` and `LED`?

Like 10 bit depth, 12 bit depth grayscale, etc.

--------------------------------------------------------------

Main reason for question
- if there is known bit depth it can be re-scaled blindly to other bit depths on user side in simple use cases
- as opposed to autocontrast or focusing on depth range window for visualization

**Comment by patrikdaniel** [comment]
The `Intensity` (`Texture`) is by default an 11-bit image (values in the range 0 - 2047). 

However, for `Texture source` = `Laser` (as opposed to `LED`), the image tends to behave more like a 10-bit image (pixels get saturated already at lower values than 2000).

**Comment by bmegli** [comment]
Thanks!

I had trouble finding this information in documentation, maybe I missed some resource.

It would be helpful if it was at least mentioned on GigEV overview or in GenICam xml.

Unless no assumptions should be made in general case.

Kind regards.
