### ISSUE TITLE
[GigEV] `Focus`/`Computed` texture source bit depth (`Scanner` mode)

### ISSUE THREAD

**Issue by bmegli** [photoneo-3d/photoneo-cpp-examples#6]
Similar to:
- #5

Can I also assume 11 bit depth for texture with `TextureSource` set to `Focus` and `Computed`?

Is there any extra prior knowledge like with `Laser`?

**Comment by patrikdaniel** [comment]
By its nature, the respective texture images for `TextureSource` = `Focus`/`Computed` are constructed from the images of the scene illuminated by the laser (without any additional image acquisition). 

Hence, the images behave similarly to those obtained with `TextureSource` = `Laser`, more like a 10-bit images.

**Comment by bmegli** [comment]
Thanks!
